Food/urls.py
# myapp/urls.py
from django.urls import path
from .views import FoodListView, FoodCreateView, FoodUpdateView, FoodDeleteView

urlpatterns = [
    path('', FoodListView.as_view(), name='food_list'),
    path('add/', FoodCreateView.as_view(), name='food_add'),
    path('<int:pk>/edit/', FoodUpdateView.as_view(), name='food_edit'),
    path('<int:pk>/delete/', FoodDeleteView.as_view(), name='food_delete'),
]

FoodManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('', include('Dashboard.urls'), name='dashboard'),
    path('foods/', include('Food.urls')),
    path('combos/', include('Combo.urls')),
    path('coupon/', include('Coupon.urls')),
    path('orders/', include('Order.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Combo/models.py
from django.db import models
from Food.models import Food

class Combo(models.Model):
    combo_code = models.CharField(max_length=100, unique=True, verbose_name="Combo Code")
    combo_name = models.CharField(max_length=255, verbose_name="Combo Name")
    unit_price = models.PositiveIntegerField(verbose_name="Unit Price")
    quantity = models.PositiveIntegerField(verbose_name="Quantity")
    image = models.ImageField(upload_to='images/', verbose_name="Image")
    products = models.ManyToManyField(Food, related_name='combos', verbose_name="Products")

    def __str__(self):
        return self.combo_name

Coupon/models.py
from django.db import models

class Coupon(models.Model):
    coupon_code = models.CharField(max_length=100, unique=True, verbose_name="Coupon Code")
    discount_rate = models.PositiveIntegerField(verbose_name="Discount Rate") 
    quantity = models.PositiveIntegerField(verbose_name="Quantity")
    expiration_date = models.DateField(verbose_name="Expiration Date")

    def __str__(self):
        return self.coupon_code

Order/models.py
from django.db import models
import string
import random
from django.utils import timezone
from Coupon.models import Coupon
from Combo.models import Combo
from Food.models import Food

def generate_random_code(length=10):
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

class Order(models.Model):
    code = models.CharField(max_length=10, unique=True, default=generate_random_code, verbose_name="Order Code")
    customer = models.CharField(max_length=255, verbose_name="Customer Name")
    phone = models.CharField(max_length=15, verbose_name="Phone Number", null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Coupon Code")
    note = models.TextField(default=None, null=True, blank=True)
    amount = models.PositiveIntegerField(verbose_name="Amount", default=0)
    payment = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f"Order {self.code} by {self.customer}"


class DetailOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Order")
    food = models.ForeignKey(Food, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Food")
    combo = models.ForeignKey(Combo, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Combo")
    quantity = models.PositiveIntegerField(verbose_name="Quantity")

    def __str__(self):
        return f"Detail of {self.order.code}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/feathericon.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/morris/morris.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	<link rel="stylehseet" href="https://cdn.oesmith.co.uk/morris-0.5.1.css">
</head>
<body>
	<div class="main-wrapper">
		<div class="header">
			<div class="header-left">
				<a href="index.html" class="logo"> <img class="rounded-circle" src="{% static 'assets/img/kfc-logo.png' %}" width="50" height="70"
						alt="logo"> <span class="logoclass">KFC</span> </a>
				<a href="index.html" class="logo logo-small"> <img src="{% static 'assets/img/kfc-logo.png' %}" alt="Logo" width="30"
						height="30"> </a>
			</div>
			<a href="javascript:void(0);" id="toggle_btn"> <i class="fe fe-text-align-left"></i> </a>
			<a class="mobile_btn" id="mobile_btn"> <i class="fas fa-bars"></i> </a>
			<ul class="nav user-menu">
				
				<li class="nav-item dropdown noti-dropdown">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <i class="fe fe-bell"></i> <span class="badge badge-pill">3</span> </a>
					<div class="dropdown-menu notifications">
						<div class="topnav-dropdown-header"> <span class="notification-title">Thông báo</span> <a href="javascript:void(0)" class="clear-noti"> Xoá tất cả </a> </div>
						<div class="noti-content">
							<ul class="notification-list">
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-01.jpg' %}">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Thạo Văn</span> đã thanh toán <span class="noti-title"> phiếu thu</span></p>
												<p class="noti-time"><span class="notification-time">4 phút trước</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-01.jpg' %}">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Thạo Văn</span> đã thanh toán <span class="noti-title"> phiếu thu</span></p>
												<p class="noti-time"><span class="notification-time">4 phút trước</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-01.jpg' %}">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Thạo Văn</span> đã thanh toán <span class="noti-title"> phiếu thu</span></p>
												<p class="noti-time"><span class="notification-time">4 phút trước</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-01.jpg' %}">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Thạo Văn</span> đã thanh toán <span class="noti-title"> phiếu thu</span></p>
												<p class="noti-time"><span class="notification-time">4 phút trước</span> </p>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
						<div class="topnav-dropdown-footer"> <a href="#">Hiển thị tất cả thông báo</a> </div>
					</div>
				</li>
				<li class="nav-item dropdown has-arrow">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <span class="user-img"><img
								class="rounded-circle" src="{% static 'assets/img/profiles/avatar-01.jpg' %}" width="31"
								alt="Soeng Souy"></span> </a>
					<div class="dropdown-menu">
						<div class="user-header">
							<div class="avatar avatar-sm"> <img src="{% static 'assets/img/profiles/avatar-01.jpg' %}" alt="User Image"
									class="avatar-img rounded-circle"> </div>
							<div class="user-text">
								<h6>PDT</h6>
								<p class="text-muted mb-0">Quản trị viên</p>
							</div>
						</div> <a class="dropdown-item" href="{% url 'profile' %}">Thông tin cá nhân</a> <a class="dropdown-item"
							href="{% url 'logout' %}">Đăng xuất</a>
					</div>
				</li>
			
			</ul>
			<div class="top-nav-search">
				<form>
					<input type="text" class="form-control" placeholder="Tìm kiếm...">
					<button class="btn" type="submit"><i class="fas fa-search"></i></button>
				</form>
			</div>

		</div>

		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li> <a class="active" href="{% url 'dashboard' %}"><i class="fas fa-home"></i> <span>Trang chủ</span></a> </li>
						<li class="list-divider"></li>
						<li class="submenu"> <a href="#"><i class="far fa-money-bill-alt"></i> <span> Hóa đơn </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'order_list' %}"> Danh sách hóa đơn </a></li>
								<li><a href="{% url 'order_create' %}"> Thêm đơn hóa đơn </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-hamburger"></i> <span>Sản phẩm</span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'food_list' %}">Danh sách sản phẩm</a></li>								 
								<li><a href="{% url 'food_add' %}">Thêm sản phẩm</a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-utensils"></i> <span> Combo </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'combo_list' %}">Danh sách combo </a></li>
								<li><a href="{% url 'combo_create' %}">Thêm combo </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-percent"></i> <span> Mã giảm giá </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'coupon_list' %}">Danh sách mã giảm giá</a></li>
								<li><a href="{% url 'coupon_create' %}">Thêm mã giảm giá</a></li>
							</ul>
						</li>
						<li class="list-divider"></li>
					</ul>
				</div>
			</div>
		</div>

        {% block content %}
        {% endblock content %}
    </div>
    <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/plugins/raphael/raphael.min.js' %}"></script>
	<script src="{% static 'assets/plugins/morris/morris.min.js' %}"></script>
	<script src="{% static 'assets/js/chart.morris.js' %}"></script>
	<script src="{% static 'assets/js/script.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>
	<script>
		$(function() {
			$('#datetimepicker3').datetimepicker({
				format: 'LT'
			});
		});
	</script>
</body>

</html>